/**
 * Shared state interface used across all SunCore SME agents.
 * This allows stateful interaction between the SME agents via the AgentKit network.
 */
export interface SunCoreState {
  /** Summary extracted from NPS data */
  npsSummary?: string;

  /** List of top-performing product names */
  topProducts?: string[];

  /** Final campaign ideas generated by the Marketing SME */
  campaignIdeas?: string;
}
